name: Train and Validate Model

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing
      run: |
        python preprocess.py

    - name: Train model
      run: |
        python train.py

    - name: Validate model
      run: |
        python model_validation.py
